### ISSUE TITLE
Create some sort of popup/display system

### ISSUE THREAD

**Issue by aleccaputo** [gregjoeval/KnightcardSignInDevice#10]
This could take a bit, but I think it would be good to have some sort of popup when you get a successful/unsuccessful sign in. 

I think all we'd need to do for code is if the insert into the database is successful, then say something like "Thank you for signing in", otherwise we have some sort of input sanitization for the sql which rejects that ;?E or ;E?+E? error. 

Basically if string starts with ;?E, database returns an error and on the screen saying "bad swipe try again".

We could use that pi screen that is lying around....3D print some sort of case for it (along with the pi).

**Comment by gregjoeval** [comment]
The python installation comes with a library (ctypes) to easily do this on Windows systems but that would only be useful during testing since Raspbian is a Linux distro. While I did comment it out, I added a message box function implementing the ctypes module anyway with commit 30.

**Comment by aleccaputo** [comment]
Done using tkinter, although is isn't particularly visually appealing
