### ISSUE TITLE
Primary Key Issue

### ISSUE THREAD

**Issue by aleccaputo** [gregjoeval/KnightcardSignInDevice#16]
Primary key is time, and even though time is is down to like milliseconds, there is a chance that someone swipes at the exact same time of day as someone else. Therefore they wouldn't get logged because the key would be a duplicate.....

But what are the chances of that...

**Comment by aleccaputo** [comment]
Combine Date and Time keys...

**Comment by gregjoeval** [comment]
Why not make date and time a composite key in the database?

**Comment by aleccaputo** [comment]
resolved by making date and time both the primary keys....
