### ISSUE TITLE
Error check for not a knight card

### ISSUE THREAD

**Issue by aleccaputo** [gregjoeval/KnightcardSignInDevice#20]
If someone swipes like a credit card

**Comment by gregjoeval** [comment]
This might not be a case we need to avoid. Unless we can access the school's database for knightcard numbers there might not be much we can do to prevent invalid numbers. What we could do is make sure the number on the card is the correct length, only made up of numbers, and starts with an '80'.

**Comment by aleccaputo** [comment]
I actually added that exact if statement to check for the 80. I just haven't committed it yet
