### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by gregjoeval** [gregjoeval/KnightcardSignInDevice#23]
I think we are getting to a point where having a configuration file would be smart. It would allow us to easily configure certain parameters without having to edit the code or change certain arguments on the command line. For example, defining the destination email for the monthly reports.

**Comment by aleccaputo** [comment]
I'm going to work on this on the plane. Downloaded a bunch of documentation for it.

**Comment by aleccaputo** [comment]
Done
