### ISSUE TITLE
Need error checking

### ISSUE THREAD

**Issue by aleccaputo** [gregjoeval/KnightcardSignInDevice#7]
error check for the ?E+?E thing

also check for valid DB connection and stuff

Maybe if we had a display that said sign in, we could have something pop up if the swipe was bad...how else would they know it didn't work other than the small red light on the card reader.

**Comment by gregjoeval** [comment]
We could also put an LED on the pi board if we can't figure out how to use the light on the card reader

**Comment by aleccaputo** [comment]
Well there is a red light on the card reader if there's an error...but i feel like people won't pay attention to it. We could take advantage of the screen that is with that pi A

**Comment by gregjoeval** [comment]
If the screen is still compatible with the newer boards then it could also help out with testing
